from pathlib import Path


def replace_once(text, old, new, label):
    if old not in text:
        raise RuntimeError(f"Marcador nao encontrado: {label}")
    return text.replace(old, new, 1)

# ========================= HOME =========================
p = Path('home.html')
s = p.read_text(encoding='utf-8')
s = replace_once(s, 'grid-template-columns: repeat(4, 1fr);', 'grid-template-columns: repeat(3, 1fr);', 'home grid cards')

s = replace_once(s, '''        <div class="card-resumo" onclick="abrirAgendados()">\n          <div class="numero" id="totalAgendadosHome">0</div>\n          <div class="texto">Agendados</div>\n        </div>''', '''        <div class="card-resumo" onclick="abrirEmpresas()">\n          <div class="numero" id="totalEmpresasHome">0</div>\n          <div class="texto">Empresas</div>\n        </div>\n\n        <div class="card-resumo" onclick="abrirAgendados()">\n          <div class="numero" id="totalAgendadosHome">0</div>\n          <div class="texto">Agendados</div>\n        </div>''', 'home card empresas')

s = replace_once(s, '''    function abrirAtencao() {\n      const q = usuarioAtualId ? "&usuario_id=" + encodeURIComponent(usuarioAtualId) : "";\n      window.location.href = "oportunidades.html?aba=atencao" + q;\n    }''', '''    function abrirAtencao() {\n      const q = usuarioAtualId ? "&usuario_id=" + encodeURIComponent(usuarioAtualId) : "";\n      window.location.href = "oportunidades.html?aba=atencao" + q;\n    }\n    function abrirEmpresas() {\n      const q = usuarioAtualId ? "&usuario_id=" + encodeURIComponent(usuarioAtualId) : "";\n      window.location.href = "oportunidades.html?aba=empresas" + q;\n    }''', 'home abrir empresas')

s = replace_once(s, '''        return status === "NOVO" &&\n          !primeiraRespostaJaEnviada(casal) &&\n          pertenceAoUsuario(casal);''', '''        return status === "NOVO" &&\n          !ehCorporativo(casal) &&\n          !primeiraRespostaJaEnviada(casal) &&\n          pertenceAoUsuario(casal);''', 'home excluir corporativo novos')

s = replace_once(s, '''    function modoAtendimentoHumano(casal) {\n      return String(casal && casal.modo_atendimento_ia || "").trim().toUpperCase() === "HUMANO";\n    }\n\n    function temVisitaAgendada(casal) {''', '''    function modoAtendimentoHumano(casal) {\n      return String(casal && casal.modo_atendimento_ia || "").trim().toUpperCase() === "HUMANO";\n    }\n\n    function ehCorporativo(casal) {\n      const tipo = String(casal && casal.tipo_evento || "").trim().toUpperCase();\n      const origem = String(casal && casal.origem || "").trim().toUpperCase();\n      return tipo === "CORPORATIVO" || origem === "META_CORPORATIVO";\n    }\n\n    function temVisitaAgendada(casal) {''', 'home helper corporativo')

s = replace_once(s, '''    function unificarOportunidadesHome(retornoOportunidades) {\n      const grupos = [\n        ...(retornoOportunidades.agendar || []),\n        ...(retornoOportunidades.resgatar || []),\n        ...(retornoOportunidades.agendados || [])\n      ];\n      const mapa = new Map();\n      grupos.forEach(casal => {\n        if (casal && casal.casal_id && pertenceAoUsuario(casal)) mapa.set(casal.casal_id, casal);\n      });\n      return Array.from(mapa.values());\n    }''', '''    function unificarTodasOportunidadesHome(retornoOportunidades) {\n      const grupos = [\n        ...(retornoOportunidades.agendar || []),\n        ...(retornoOportunidades.resgatar || []),\n        ...(retornoOportunidades.agendados || [])\n      ];\n      const mapa = new Map();\n      grupos.forEach(casal => {\n        if (casal && casal.casal_id) mapa.set(casal.casal_id, casal);\n      });\n      return Array.from(mapa.values());\n    }\n\n    function unificarOportunidadesHome(retornoOportunidades) {\n      return unificarTodasOportunidadesHome(retornoOportunidades).filter(pertenceAoUsuario);\n    }''', 'home unificar compartilhado')

s = replace_once(s, '''        if (temVisitaAgendada(casal)) return false;\n        if (status === "PERDIDO" || status === "GANHO") return false;\n        return modoAtendimentoHumano(casal);''', '''        if (temVisitaAgendada(casal)) return false;\n        if (ehCorporativo(casal)) return false;\n        if (status === "PERDIDO" || status === "GANHO") return false;\n        return modoAtendimentoHumano(casal);''', 'home atencao exclui empresas')

s = replace_once(s, '''    function contarAgendadosDaCHO(retornoOportunidades) {\n      return unificarOportunidadesHome(retornoOportunidades).filter(temVisitaAgendada).length;\n    }''', '''    function contarEmpresasDaCHO(retornoOportunidades) {\n      return unificarTodasOportunidadesHome(retornoOportunidades).filter(casal => {\n        const status = normalizarStatus(casal.status_casal);\n        if (temVisitaAgendada(casal)) return false;\n        if (status === "PERDIDO" || status === "GANHO") return false;\n        return ehCorporativo(casal);\n      }).length;\n    }\n\n    function contarAgendadosDaCHO(retornoOportunidades) {\n      return unificarOportunidadesHome(retornoOportunidades).filter(temVisitaAgendada).length;\n    }''', 'home contar empresas')

s = replace_once(s, '''        if (temVisitaAgendada(casal)) return false;\n        if (modoAtendimentoHumano(casal)) return false;''', '''        if (temVisitaAgendada(casal)) return false;\n        if (ehCorporativo(casal)) return false;\n        if (modoAtendimentoHumano(casal)) return false;''', 'home oportunidades exclui empresas')

s = replace_once(s, '''          const totalAgendadosHome = document.getElementById("totalAgendadosHome");\n          const totalAtencaoHome = document.getElementById("totalAtencaoHome");\n          if (totalAgendadosHome) totalAgendadosHome.textContent = String(contarAgendadosDaCHO(dadosOportunidades));\n          if (totalAtencaoHome) totalAtencaoHome.textContent = String(contarAtencaoDaCHO(dadosOportunidades));''', '''          const totalEmpresasHome = document.getElementById("totalEmpresasHome");\n          const totalAgendadosHome = document.getElementById("totalAgendadosHome");\n          const totalAtencaoHome = document.getElementById("totalAtencaoHome");\n          if (totalEmpresasHome) totalEmpresasHome.textContent = String(contarEmpresasDaCHO(dadosOportunidades));\n          if (totalAgendadosHome) totalAgendadosHome.textContent = String(contarAgendadosDaCHO(dadosOportunidades));\n          if (totalAtencaoHome) totalAtencaoHome.textContent = String(contarAtencaoDaCHO(dadosOportunidades));''', 'home set total empresas')

s = replace_once(s, '''        totalNovos.textContent = "0";\n        totalOportunidadesEl.textContent = "0";''', '''        totalNovos.textContent = "0";\n        totalOportunidadesEl.textContent = "0";\n        const totalEmpresasHome = document.getElementById("totalEmpresasHome");\n        if (totalEmpresasHome) totalEmpresasHome.textContent = "0";''', 'home erro total empresas')
p.write_text(s, encoding='utf-8')

# ===================== OPORTUNIDADES ====================
p = Path('oportunidades.html')
s = p.read_text(encoding='utf-8')
s = replace_once(s, 'grid-template-columns: repeat(4, 1fr);', 'grid-template-columns: repeat(3, 1fr);', 'opp grid cards')

s = replace_once(s, '''    .card-resumo.atencao.active {\n      background: #fff3e8;\n      border-color: #e3b489;\n    }''', '''    .card-resumo.atencao.active {\n      background: #fff3e8;\n      border-color: #e3b489;\n    }\n\n    .card-resumo.empresas .numero,\n    .card-resumo.empresas .texto {\n      color: #4e7772;\n    }\n\n    .card-resumo.empresas.active {\n      background: #edf7f5;\n      border-color: #9ec9c2;\n    }''', 'opp css empresas')

s = replace_once(s, '''        <div class="card-resumo resgatar" id="card-resgatar" onclick="trocarAba('resgatar')">''', '''        <div class="card-resumo empresas" id="card-empresas" onclick="trocarAba('empresas')">\n          <div class="numero" id="totalEmpresas">0</div>\n          <div class="texto">Empresas</div>\n        </div>\n\n        <div class="card-resumo resgatar" id="card-resgatar" onclick="trocarAba('resgatar')">''', 'opp card empresas')

s = replace_once(s, '''      agendados: [],\n      atencao: [],''', '''      agendados: [],\n      empresas: [],\n      atencao: [],''', 'opp dados empresas')
s = replace_once(s, '''        agendados: 0,\n        atencao: 0,''', '''        agendados: 0,\n        empresas: 0,\n        atencao: 0,''', 'opp totais empresas')
s = replace_once(s, '''      agendados: "Visitas agendadas",\n      atencao: "Atendimentos assumidos por você",''', '''      agendados: "Visitas agendadas",\n      empresas: "Empresas para atendimento",\n      atencao: "Atendimentos assumidos por você",''', 'opp titulo empresas')
s = replace_once(s, '''      if (aba === "resgatar" || aba === "encerrados" || aba === "agendados" || aba === "atencao" || aba === "agendar") {''', '''      if (aba === "resgatar" || aba === "encerrados" || aba === "agendados" || aba === "empresas" || aba === "atencao" || aba === "agendar") {''', 'opp aba empresas')

s = replace_once(s, '''    function modoAtendimentoHumano(casal) {\n      return String(casal && casal.modo_atendimento_ia || "").trim().toUpperCase() === "HUMANO";\n    }\n\n    function temVisitaAgendada(casal) {''', '''    function modoAtendimentoHumano(casal) {\n      return String(casal && casal.modo_atendimento_ia || "").trim().toUpperCase() === "HUMANO";\n    }\n\n    function ehCorporativo(casal) {\n      const tipo = String(casal && casal.tipo_evento || "").trim().toUpperCase();\n      const origem = String(casal && casal.origem || "").trim().toUpperCase();\n      return tipo === "CORPORATIVO" || origem === "META_CORPORATIVO";\n    }\n\n    function temVisitaAgendada(casal) {''', 'opp helper corp')

s = replace_once(s, '''      const unicos = Array.from(mapa.values()).filter(pertenceAoUsuario);\n\n      const agendados = unicos''', '''      const todosUnicos = Array.from(mapa.values());\n      const unicos = todosUnicos.filter(pertenceAoUsuario);\n\n      const agendados = unicos''', 'opp todos unicos')

s = replace_once(s, '''      const encerrados = unicos.filter(casal => normalizarStatus(casal.status_casal) === "PERDIDO");\n\n      const atencao = unicos.filter(casal => {''', '''      const encerrados = unicos.filter(casal => normalizarStatus(casal.status_casal) === "PERDIDO");\n\n      // EMPRESAS e uma fila compartilhada entre usuarios autenticados.\n      // A responsabilidade continua registrada em consultora_responsavel, mas nao limita a visualizacao.\n      const empresas = todosUnicos.filter(casal => {\n        const status = normalizarStatus(casal.status_casal);\n        if (temVisitaAgendada(casal)) return false;\n        if (status === "PERDIDO" || status === "GANHO") return false;\n        return ehCorporativo(casal);\n      });\n\n      const atencao = unicos.filter(casal => {''', 'opp empresas compartilhada')

s = replace_once(s, '''        if (temVisitaAgendada(casal)) return false;\n        if (status === "PERDIDO" || status === "GANHO") return false;\n        return modoAtendimentoHumano(casal);''', '''        if (temVisitaAgendada(casal)) return false;\n        if (ehCorporativo(casal)) return false;\n        if (status === "PERDIDO" || status === "GANHO") return false;\n        return modoAtendimentoHumano(casal);''', 'opp atencao exclui corp')

# duas ocorrencias: agendar e resgatar
s = replace_once(s, '''        if (temVisitaAgendada(casal) || modoAtendimentoHumano(casal)) return false;\n        return status === "EM_ATENDIMENTO" ||''', '''        if (temVisitaAgendada(casal) || ehCorporativo(casal) || modoAtendimentoHumano(casal)) return false;\n        return status === "EM_ATENDIMENTO" ||''', 'opp agendar exclui corp')
s = replace_once(s, '''        if (temVisitaAgendada(casal) || modoAtendimentoHumano(casal)) return false;\n        return status === "VISITOU_NAO_FECHOU";''', '''        if (temVisitaAgendada(casal) || ehCorporativo(casal) || modoAtendimentoHumano(casal)) return false;\n        return status === "VISITOU_NAO_FECHOU";''', 'opp resgatar exclui corp')

s = replace_once(s, '''        agendados,\n        atencao,''', '''        agendados,\n        empresas,\n        atencao,''', 'opp return empresas')
s = replace_once(s, '''          agendados: agendados.length,\n          atencao: atencao.length,''', '''          agendados: agendados.length,\n          empresas: empresas.length,\n          atencao: atencao.length,''', 'opp total empresas return')
s = replace_once(s, '''        ["agendar", "resgatar", "agendados", "atencao", "encerrados"].forEach(grupo => {''', '''        ["agendar", "resgatar", "agendados", "empresas", "atencao", "encerrados"].forEach(grupo => {''', 'opp propostas empresas')

s = replace_once(s, '''        const nome = nomeCasal(casal);\n        const sonhos = formatarEncantamentos(casal.encantamentos_principais);''', '''        const corporativo = tipo === "empresas" || ehCorporativo(casal);\n        const nome = corporativo\n          ? (casal.nome_empresa || casal.nome_contato || "Empresa sem nome")\n          : nomeCasal(casal);\n        const sonhos = corporativo ? "" : formatarEncantamentos(casal.encantamentos_principais);''', 'opp nome empresas')

s = replace_once(s, '''        if (tipo === "atencao") {\n          statusTexto = "Atendimento humano";\n          alerta = "A Milene está pausada. Este atendimento está sob sua responsabilidade.";\n        }''', '''        if (tipo === "empresas") {\n          statusTexto = "Evento corporativo";\n          alerta = "Atendimento humano. Lead corporativo fora da fila de casamentos.";\n        }\n\n        if (tipo === "atencao") {\n          statusTexto = "Atendimento humano";\n          alerta = "A Milene está pausada. Este atendimento está sob sua responsabilidade.";\n        }''', 'opp status empresas')

s = replace_once(s, '''        card.innerHTML = `\n          <div class="casal-top">''', '''        const linhaEvento = corporativo\n          ? `<div class="linha-info">📅 ${casal.data_evento || "Data não informada"} &nbsp; | &nbsp; 👥 ${casal.quantidade_pessoas || "--"} pessoas</div>`\n          : `<div class="linha-info">📅 ${casal.data_casamento || "Data não informada"} &nbsp; | &nbsp; 👥 ${casal.quantidade_convidados || "--"} convidados</div>`;\n        const contatoEmpresa = corporativo && casal.nome_contato\n          ? `<div class="linha-info">👤 Contato: ${casal.nome_contato}</div>`\n          : "";\n        const sonhosHtml = corporativo ? "" : `<div class="sonhos">✨ Sonhos: ${sonhos}</div>`;\n\n        card.innerHTML = `\n          <div class="casal-top">''', 'opp vars card empresa')

s = replace_once(s, '''          <div class="linha-info">📅 ${casal.data_casamento || "Data não informada"} &nbsp; | &nbsp; 👥 ${casal.quantidade_convidados || "--"} convidados</div>\n\n          <div class="linha-info">⏱ ${formatarContato(casal)}</div>\n\n          <div class="sonhos">✨ Sonhos: ${sonhos}</div>\n          <div class="linha-info">${linhaProposta(casal)}</div>''', '''          ${linhaEvento}\n          ${contatoEmpresa}\n          <div class="linha-info">⏱ ${formatarContato(casal)}</div>\n\n          ${sonhosHtml}\n          <div class="linha-info">${linhaProposta(casal)}</div>''', 'opp corpo card empresas')

s = replace_once(s, '''        document.getElementById("totalResgatar").textContent = dados.totais.resgatar;\n        document.getElementById("totalAtencao").textContent = dados.totais.atencao;''', '''        document.getElementById("totalResgatar").textContent = dados.totais.resgatar;\n        document.getElementById("totalEmpresas").textContent = dados.totais.empresas;\n        document.getElementById("totalAtencao").textContent = dados.totais.atencao;''', 'opp set total empresas')
p.write_text(s, encoding='utf-8')

# ====================== ATENDIMENTO =====================
p = Path('atendimento.html')
s = p.read_text(encoding='utf-8')

s = replace_once(s, '''    function nomeCasal(casal) {\n      const pessoa1 = casal.nome_pessoa_1 || casal.nome_noiva || "";\n      const pessoa2 = casal.nome_pessoa_2 || casal.nome_noivo || "";\n\n      if (pessoa1 && pessoa2) {\n        return pessoa1 + " ❤️ " + pessoa2;\n      }\n\n      return pessoa1 || pessoa2 || casal.nome_contato || "Casal sem nome";\n    }''', '''    function nomeCasal(casal) {\n      const pessoa1 = casal.nome_pessoa_1 || casal.nome_noiva || "";\n      const pessoa2 = casal.nome_pessoa_2 || casal.nome_noivo || "";\n\n      if (pessoa1 && pessoa2) {\n        return pessoa1 + " ❤️ " + pessoa2;\n      }\n\n      return pessoa1 || pessoa2 || casal.nome_contato || "Casal sem nome";\n    }\n\n    function ehCorporativo(casal) {\n      const tipo = String(casal && casal.tipo_evento || "").trim().toUpperCase();\n      const origem = String(casal && casal.origem || "").trim().toUpperCase();\n      return tipo === "CORPORATIVO" || origem === "META_CORPORATIVO";\n    }\n\n    function nomeRegistro(casal) {\n      if (ehCorporativo(casal)) return casal.nome_empresa || casal.nome_contato || "Empresa sem nome";\n      return nomeCasal(casal);\n    }\n\n    function formatarDataEvento(casal) {\n      if (ehCorporativo(casal)) return casal.data_evento ? "📅 " + casal.data_evento : "📅 Data não informada";\n      return formatarDataCasamento(casal.data_casamento);\n    }\n\n    function formatarQuantidadeEvento(casal) {\n      if (ehCorporativo(casal)) return casal.quantidade_pessoas ? "👥 " + casal.quantidade_pessoas + " pessoas" : "👥 Quantidade não informada";\n      return formatarConvidados(casal.quantidade_convidados);\n    }\n\n    function configurarAtendimentoPorTipo(casal) {\n      const corporativo = ehCorporativo(casal);\n      const navAtencao = document.getElementById("navAtencao");\n      const navDisponibilidade = document.getElementById("navDisponibilidade");\n      const propostaResumo = document.getElementById("propostaResumo");\n      if (navAtencao) navAtencao.style.display = corporativo ? "none" : "";\n      if (navDisponibilidade) navDisponibilidade.style.display = corporativo ? "none" : "";\n      if (propostaResumo) propostaResumo.style.display = corporativo ? "none" : "";\n      if (corporativo) {\n        const reviewDock = document.getElementById("reviewDock");\n        if (reviewDock) reviewDock.classList.remove("show", "urgent");\n      }\n      atualizarDockModoHumano();\n    }''', 'atendimento helpers multi evento')

s = replace_once(s, '''        document.getElementById("nomeCasal").textContent = nomeCasal(casal);\n        document.getElementById("dataCasamento").textContent = formatarDataCasamento(casal.data_casamento);\n        document.getElementById("qtdConvidados").textContent = formatarConvidados(casal.quantidade_convidados);\n        atualizarResumoPropostaCabecalho(casal);\n        carregarResumoPropostaCasal(casalAtualId);\n        renderizarEncantamentos(casal.encantamentos_principais);\n        await carregarHistoricoConversas({ forcar: true, forcarScroll: true });\n        iniciarAtualizacaoAutomaticaConversas();\n        await carregarRevisaoPendenteAtual({ tocarSom: false });\n        iniciarAtualizacaoAutomaticaRevisoes();\n        iniciarAlarmeRevisaoAtendimento();''', '''        const corporativo = ehCorporativo(casal);\n        document.getElementById("nomeCasal").textContent = nomeRegistro(casal);\n        document.getElementById("dataCasamento").textContent = formatarDataEvento(casal);\n        document.getElementById("qtdConvidados").textContent = formatarQuantidadeEvento(casal);\n        atualizarResumoPropostaCabecalho(casal);\n        if (!corporativo) carregarResumoPropostaCasal(casalAtualId);\n        renderizarEncantamentos(corporativo ? "" : casal.encantamentos_principais);\n        configurarAtendimentoPorTipo(casal);\n        await carregarHistoricoConversas({ forcar: true, forcarScroll: true });\n        iniciarAtualizacaoAutomaticaConversas();\n        if (!corporativo) {\n          await carregarRevisaoPendenteAtual({ tocarSom: false });\n          iniciarAtualizacaoAutomaticaRevisoes();\n          iniciarAlarmeRevisaoAtendimento();\n        } else {\n          esconderRevisaoPendente();\n        }''', 'atendimento carregar corporativo')

s = replace_once(s, '''    function atualizarDockModoHumano() {\n      const humanDock = document.getElementById("humanModeDock");\n      const modo = String(casalAtual.modo_atendimento_ia || "").toUpperCase();\n      humanDock.classList.toggle("show", modo === "HUMANO");\n    }''', '''    function atualizarDockModoHumano() {\n      const humanDock = document.getElementById("humanModeDock");\n      const humanText = document.getElementById("humanModeText");\n      const humanBtn = document.getElementById("humanModeBtn");\n      const modo = String(casalAtual.modo_atendimento_ia || "").toUpperCase();\n      const corporativo = ehCorporativo(casalAtual);\n      humanDock.classList.toggle("show", modo === "HUMANO");\n      if (corporativo) {\n        if (humanText) humanText.innerHTML = "Atendimento corporativo sob responsabilidade humana.<br>A Milene não participa desta rota.";\n        if (humanBtn) humanBtn.style.display = "none";\n      } else {\n        if (humanText) humanText.innerHTML = "Atendimento assumido pelo humano.<br>A Milene está pausada para este casal.";\n        if (humanBtn) humanBtn.style.display = "";\n      }\n    }''', 'atendimento dock humano')

s = replace_once(s, '''    async function devolverAtendimentoParaMilene() {''', '''    async function devolverAtendimentoParaMilene() {\n      if (ehCorporativo(casalAtual)) {\n        alert("Atendimentos corporativos permanecem em modo humano.");\n        return;\n      }''', 'atendimento bloquear devolver milene')

s = replace_once(s, '''    async function marcarAtencao() {\n      if (!casalAtualId) return;''', '''    async function marcarAtencao() {\n      if (!casalAtualId) return;\n      if (ehCorporativo(casalAtual)) {\n        alert("Este atendimento corporativo permanece na fila EMPRESAS ate o agendamento.");\n        return;\n      }''', 'atendimento bloquear atencao corp')

s = replace_once(s, '''        carregarHistoricoConversas({ forcar: true, forcarScroll: true });\n        carregarRevisaoPendenteAtual({ tocarSom: false });''', '''        carregarHistoricoConversas({ forcar: true, forcarScroll: true });\n        if (!ehCorporativo(casalAtual)) carregarRevisaoPendenteAtual({ tocarSom: false });''', 'atendimento visibility review corp')

s = replace_once(s, '''    <section class="human-mode-dock" id="humanModeDock">\n      <div class="human-mode-text">''', '''    <section class="human-mode-dock" id="humanModeDock">\n      <div class="human-mode-text" id="humanModeText">''', 'atendimento human text id')
s = replace_once(s, '''      <button class="human-mode-btn" type="button" onclick="devolverAtendimentoParaMilene()">DEVOLVER PARA MILENE</button>''', '''      <button class="human-mode-btn" id="humanModeBtn" type="button" onclick="devolverAtendimentoParaMilene()">DEVOLVER PARA MILENE</button>''', 'atendimento human btn id')
s = replace_once(s, '''      <div class="nav-item" onclick="abrirDisponibilidade()">''', '''      <div class="nav-item" id="navDisponibilidade" onclick="abrirDisponibilidade()">''', 'atendimento nav disponibilidade id')
p.write_text(s, encoding='utf-8')

# ==================== SERVICE WORKER ====================
p = Path('service-worker.js')
s = p.read_text(encoding='utf-8')
s = replace_once(s, 'crm-margo-pwa-v14-multi-evento-20260825', 'crm-margo-pwa-v15-empresas-20260825', 'cache v15')
p.write_text(s, encoding='utf-8')

# ========================= README =======================
Path('README_V1_15_EMPRESAS.txt').write_text('''CRM APP V1.15 — EMPRESAS\n\nOBJETIVO\nCriar a fila visual EMPRESAS para leads corporativos, sem mistura com oportunidades de casamento.\n\nIDENTIFICACAO\n- tipo_evento = CORPORATIVO; ou\n- origem = META_CORPORATIVO.\n\nPRECEDENCIA\n1. AGENDADOS: qualquer evento com visita agendada.\n2. EMPRESAS: corporativo ativo sem visita agendada.\n3. ATENCAO: humano nao corporativo sem visita.\n4. OPORTUNIDADES/AGENDAR/RESGATAR: somente nao corporativos.\n5. ENCERRADOS: arquivo de perdas.\n\nVISIBILIDADE\nEMPRESAS e fila compartilhada entre usuarios autenticados; consultora_responsavel continua sendo responsabilidade, nao filtro de visibilidade da fila.\n\nATENDIMENTO CORPORATIVO\n- nome da empresa no cabecalho quando disponivel;\n- data_evento e quantidade_pessoas no lugar dos campos de casamento;\n- rota permanece HUMANO;\n- controles de devolver para Milene e Atenção ficam indisponiveis;\n- Consultar Data de casamento fica oculto;\n- Agendar continua disponivel.\n\nARQUIVOS\n- home.html\n- oportunidades.html\n- atendimento.html\n- service-worker.js\n''', encoding='utf-8')

print('V1.15 patch aplicado com sucesso')
